<?php

namespace Database\Factories;

use App\Models\Product;
use App\Models\Report;
use App\Models\User;
use App\View\Components\StatusBadge;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;

/**
 * The tracking reference (ref) is generated by the Report model when it is created.
 *
 * @extends Factory<Report>
 */
class ReportFactory extends Factory
{
    public const DESCRIPTIONS = [
        'greenwashing' => 'L\'allégation environnementale mise en avant ne correspond pas aux informations disponibles sur la plateforme. Je joins une photo de l\'emballage et le lien de la fiche.',
        'misleading_footprint' => 'Les chiffres d\'empreinte présentés au consommateur semblent incomplets par rapport aux étapes de transport visibles dans la traçabilité.',
        'dubious_certification' => 'Le label affiché ne figure pas dans la liste des certifications vérifiées de cet acteur. Je n\'ai trouvé aucun numéro de certificat.',
        'traceability_error' => 'Une incohérence apparaît dans la chaîne de traçabilité : les dates ou lieux ne correspondent pas entre deux étapes.',
        'health_quality' => 'Le produit reçu présente un défaut qui pourrait poser un problème de qualité ou de sécurité alimentaire.',
        'other' => 'Remarque générale concernant les informations affichées pour cette cible.',
    ];

    private const TITLES = [
        'greenwashing' => ['Mention « naturel » non justifiée', 'Visuel « zéro déchet » sur un emballage plastique'],
        'misleading_footprint' => ['Distance parcourue sous-estimée', 'Éco-score affiché différent de la fiche'],
        'dubious_certification' => ['Logo bio sans numéro de certificat', 'Label local affiché hors zone'],
        'traceability_error' => ['Date d\'étape incohérente', 'Lieu de transformation différent de l\'étiquette'],
        'health_quality' => ['Emballage endommagé à la réception', 'Date limite peu lisible'],
        'other' => ['Question sur l\'origine du produit', 'Information manquante sur la fiche'],
    ];

    private const RESOLUTIONS = [
        'confirmed' => 'Allégation retirée par l\'acteur après échange avec la modération.',
        'resolved' => 'Correction effectuée par l\'acteur et vérifiée par la modération.',
        'rejected' => 'Les justificatifs fournis confirment l\'information affichée.',
    ];

    public function definition(): array
    {
        $type = fake()->randomElement(array_keys(self::DESCRIPTIONS));
        $status = fake()->randomElement(array_keys(StatusBadge::options('report')));
        $createdAt = fake()->dateTimeBetween('-12 months');

        return [
            'type' => $type,
            'reportable_type' => 'product',
            'reportable_id' => Product::factory(),
            'title' => fake()->randomElement(self::TITLES[$type]),
            'description' => self::DESCRIPTIONS[$type],
            'status' => $status,
            'priority' => fake()->randomElement(array_keys(StatusBadge::options('priority'))),
            'reporter_id' => User::factory(),
            'assignee_id' => null,
            'resolution' => self::RESOLUTIONS[$status] ?? null,
            'created_at' => $createdAt,
            'updated_at' => $createdAt,
        ];
    }

    /** Targets another reportable record (product, actor or certification). */
    public function about(Model $record): static
    {
        return $this->state(fn (array $attributes) => [
            'reportable_type' => $record->getMorphClass(),
            'reportable_id' => $record->getKey(),
        ]);
    }

    public function open(): static
    {
        return $this->state(fn (array $attributes) => ['status' => fake()->randomElement(Report::OPEN_STATUSES), 'resolution' => null]);
    }
}
